/**
 * Datos de ejemplo que usa la web cuando NO hay credenciales de Airtable
 * (desarrollo local, previews sin secretos). Cifras y habitaciones inventadas:
 * las reales las pone el hotel en Airtable sin tocar código.
 *
 * Son las 10 habitaciones reales del hotel que se ofrecen como espacio
 * privado para ver la mascletá desde el balcón (ver docs/airtable-esquema.md).
 */
import type { Room } from './booking';

export const FIXTURE_ROOMS: Room[] = [
  {
    id: 'fix-214',
    slug: 'habitacion-214',
    roomNumber: '214',
    floor: '2ª planta',
    capacity: 2,
    bed: 'Cama doble',
    price: 160,
    cupo: 1,
    descriptionEs: 'Balcón directo a la Plaza del Ayuntamiento, en primera línea de la mascletá.',
    descriptionEn: 'Balcony right onto Plaza del Ayuntamiento, front row for the mascletá.',
    photos: [],
    order: 1,
  },
  {
    id: 'fix-219',
    slug: 'habitacion-219',
    roomNumber: '219',
    floor: '2ª planta',
    capacity: 3,
    bed: 'Cama doble y sofá cama',
    price: 190,
    cupo: 1,
    descriptionEs: 'Balcón amplio a la plaza, ideal para ir en familia.',
    descriptionEn: 'A wide balcony over the square, great for families.',
    photos: [],
    order: 2,
  },
  {
    id: 'fix-305',
    slug: 'habitacion-305',
    roomNumber: '305',
    floor: '3ª planta',
    capacity: 4,
    bed: 'Dos camas dobles',
    price: 210,
    cupo: 1,
    descriptionEs: 'Dos camas dobles y balcón a la plaza, pensada para grupos de amigos.',
    descriptionEn: 'Two double beds and a balcony over the square, great for a group of friends.',
    photos: [],
    order: 3,
  },
  {
    id: 'fix-317',
    slug: 'habitacion-317',
    roomNumber: '317',
    floor: '3ª planta',
    capacity: 4,
    bed: 'Cama doble o dos camas (según disponibilidad)',
    price: 200,
    cupo: 1,
    descriptionEs: 'Tu balcón privado en plena Plaza del Ayuntamiento.',
    descriptionEn: 'Your private balcony right on Plaza del Ayuntamiento.',
    photos: [],
    order: 4,
  },
  {
    id: 'fix-322',
    slug: 'habitacion-322',
    roomNumber: '322',
    floor: '3ª planta',
    capacity: 2,
    bed: 'Cama doble',
    price: 175,
    cupo: 1,
    descriptionEs: 'Mirador con vistas laterales a la plaza, más recogido.',
    descriptionEn: 'A viewpoint room with a side view of the square, cosier.',
    photos: [],
    order: 5,
  },
  {
    id: 'fix-401',
    slug: 'habitacion-401',
    roomNumber: '401',
    floor: '4ª planta',
    capacity: 6,
    bed: 'Habitación familiar, tres camas',
    price: 320,
    cupo: 1,
    descriptionEs: 'La más grande de la casa: balcón amplio y sitio de sobra para todo el grupo.',
    descriptionEn: 'The largest room in the hotel: a wide balcony and plenty of room for the whole group.',
    photos: [],
    order: 6,
  },
  {
    id: 'fix-408',
    slug: 'habitacion-408',
    roomNumber: '408',
    floor: '4ª planta',
    capacity: 4,
    bed: 'Dos camas dobles',
    price: 230,
    cupo: 1,
    descriptionEs: 'Buena altura sobre la plaza, con dos camas dobles y balcón.',
    descriptionEn: 'A good height over the square, with two double beds and a balcony.',
    photos: [],
    order: 7,
  },
  {
    id: 'fix-415',
    slug: 'habitacion-415',
    roomNumber: '415',
    floor: '4ª planta',
    capacity: 2,
    bed: 'Cama doble',
    price: 190,
    cupo: 1,
    descriptionEs: 'Balcón amplio en una de las plantas más altas del hotel.',
    descriptionEn: 'A wide balcony on one of the hotel’s highest floors.',
    photos: [],
    order: 8,
  },
  {
    id: 'fix-502',
    slug: 'habitacion-502',
    roomNumber: '502',
    floor: '5ª planta (ático)',
    capacity: 3,
    bed: 'Cama doble y cama nido',
    price: 260,
    cupo: 1,
    descriptionEs: 'Ático con terraza privada: la mejor vista de la plaza de todo el hotel.',
    descriptionEn: 'Top-floor room with a private terrace: the best view of the square in the hotel.',
    photos: [],
    order: 9,
  },
  {
    id: 'fix-510',
    slug: 'habitacion-510',
    roomNumber: '510',
    floor: '5ª planta (ático)',
    capacity: 2,
    bed: 'Cama doble',
    price: 240,
    cupo: 1,
    descriptionEs: 'Ático con terraza privada, íntimo y en primera línea de la mascletá.',
    descriptionEn: 'Top-floor room with a private terrace, intimate and front row for the mascletá.',
    photos: [],
    order: 10,
  },
];
