/**
 * Datos de ejemplo que usa la web cuando NO hay credenciales de Airtable
 * (desarrollo local, previews sin secretos). Cifras y habitaciones inventadas:
 * las reales las pone el hotel en Airtable sin tocar código.
 *
 * Son las 10 habitaciones reales del hotel que se ofrecen como espacio
 * privado para ver la mascletá desde el balcón (ver docs/airtable-esquema.md).
 * Las 10 admiten hasta 4 personas; el precio varía según cuántas se apunten.
 */
import type { Room } from './booking';

export const FIXTURE_ROOMS: Room[] = [
  {
    id: 'fix-214',
    slug: 'habitacion-214',
    roomNumber: '214',
    floor: '2ª planta',
    capacity: 4,
    prices: { 2: 150, 3: 175, 4: 200 },
    cupo: 1,
    descriptionEs: 'Balcón directo a la Plaza del Ayuntamiento, en primera línea de la mascletá.',
    descriptionEn: 'Balcony right onto Plaza del Ayuntamiento, front row for the mascletá.',
    photos: [],
    order: 1,
  },
  {
    id: 'fix-219',
    slug: 'habitacion-219',
    roomNumber: '219',
    floor: '2ª planta',
    capacity: 4,
    prices: { 2: 170, 3: 195, 4: 220 },
    cupo: 1,
    descriptionEs: 'Balcón amplio a la plaza, ideal para ir en familia.',
    descriptionEn: 'A wide balcony over the square, great for families.',
    photos: [],
    order: 2,
  },
  {
    id: 'fix-305',
    slug: 'habitacion-305',
    roomNumber: '305',
    floor: '3ª planta',
    capacity: 4,
    prices: { 2: 190, 3: 215, 4: 240 },
    cupo: 1,
    descriptionEs: 'Balcón a la plaza, pensada para grupos de amigos.',
    descriptionEn: 'A balcony over the square, great for a group of friends.',
    photos: [],
    order: 3,
  },
  {
    id: 'fix-317',
    slug: 'habitacion-317',
    roomNumber: '317',
    floor: '3ª planta',
    capacity: 4,
    prices: { 2: 180, 3: 205, 4: 230 },
    cupo: 1,
    descriptionEs: 'Tu balcón privado en plena Plaza del Ayuntamiento.',
    descriptionEn: 'Your private balcony right on Plaza del Ayuntamiento.',
    photos: [],
    order: 4,
  },
  {
    id: 'fix-322',
    slug: 'habitacion-322',
    roomNumber: '322',
    floor: '3ª planta',
    capacity: 4,
    prices: { 2: 160, 3: 185, 4: 210 },
    cupo: 1,
    descriptionEs: 'Mirador con vistas laterales a la plaza, más recogido.',
    descriptionEn: 'A viewpoint room with a side view of the square, cosier.',
    photos: [],
    order: 5,
  },
  {
    id: 'fix-401',
    slug: 'habitacion-401',
    roomNumber: '401',
    floor: '4ª planta',
    capacity: 4,
    prices: { 2: 260, 3: 290, 4: 320 },
    cupo: 1,
    descriptionEs: 'La más grande de la casa: balcón amplio y sitio de sobra para todo el grupo.',
    descriptionEn: 'The largest room in the hotel: a wide balcony and plenty of room for the whole group.',
    photos: [],
    order: 6,
  },
  {
    id: 'fix-408',
    slug: 'habitacion-408',
    roomNumber: '408',
    floor: '4ª planta',
    capacity: 4,
    prices: { 2: 210, 3: 235, 4: 260 },
    cupo: 1,
    descriptionEs: 'Buena altura sobre la plaza, con balcón.',
    descriptionEn: 'A good height over the square, with a balcony.',
    photos: [],
    order: 7,
  },
  {
    id: 'fix-415',
    slug: 'habitacion-415',
    roomNumber: '415',
    floor: '4ª planta',
    capacity: 4,
    prices: { 2: 170, 3: 195, 4: 220 },
    cupo: 1,
    descriptionEs: 'Balcón amplio en una de las plantas más altas del hotel.',
    descriptionEn: 'A wide balcony on one of the hotel’s highest floors.',
    photos: [],
    order: 8,
  },
  {
    id: 'fix-502',
    slug: 'habitacion-502',
    roomNumber: '502',
    floor: '5ª planta (ático)',
    capacity: 4,
    prices: { 2: 230, 3: 255, 4: 280 },
    cupo: 1,
    descriptionEs: 'Ático con terraza privada: la mejor vista de la plaza de todo el hotel.',
    descriptionEn: 'Top-floor room with a private terrace: the best view of the square in the hotel.',
    photos: [],
    order: 9,
  },
  {
    id: 'fix-510',
    slug: 'habitacion-510',
    roomNumber: '510',
    floor: '5ª planta (ático)',
    capacity: 4,
    prices: { 2: 220, 3: 245, 4: 270 },
    cupo: 1,
    descriptionEs: 'Ático con terraza privada, íntimo y en primera línea de la mascletá.',
    descriptionEn: 'Top-floor room with a private terrace, intimate and front row for the mascletá.',
    photos: [],
    order: 10,
  },
];
